#ifndef N_COLOR_H
#define N_COLOR_H

typedef enum N_COLOR
{
N_COLOR_BLACK = 0,
N_COLOR_BLUE = 1,
N_COLOR_GREEN = 2,
N_COLOR_CYAN = 3,
N_COLOR_RED = 4,
N_COLOR_MAGENTA = 5,
N_COLOR_BROWN = 6,
N_COLOR_LIGHT_GREY = 7,
N_COLOR_DARK_GREY = 8,
N_COLOR_LIGHT_BLUE = 9,
N_COLOR_LIGHT_GREEN = 10,
N_COLOR_LIGHT_CYAN = 11,
N_COLOR_LIGHT_RED = 12,
N_COLOR_LIGHT_MAGENTA = 13,
N_COLOR_LIGHT_BROWN = 14,
N_COLOR_WHITE = 15
} N_Color;
#endif
