#ifndef MUNIXCC_TOKENS_H
#define MUNIXCC_TOKENS_H

#include <stdint.h>
#include <stddef.h>

/*
 *
 * Este archivo contiene los tokens y algunas cosas más
 *
 */

typedef enum {
	C_TOKEN_EOF, // importante saber cuando acaba el archivo
	// keywords
	C_TOKEN_AUTO,
	C_TOKEN_DOUBLE,
	C_TOKEN_INT,
	C_TOKEN_STRUCT,
	C_TOKEN_BREAK,
	C_TOKEN_ELSE,
	C_TOKEN_LONG,
	C_TOKEN_SWITCH,
	C_TOKEN_CASE,
	C_TOKEN_ENUM,
	C_TOKEN_REGISTER,
	C_TOKEN_TYPEDEF,
	C_TOKEN_CHAR,
	C_TOKEN_EXTERN,
	C_TOKEN_RETURN,
	C_TOKEN_UNION,
	C_TOKEN_CONST,
	C_TOKEN_FLOAT,
	C_TOKEN_SHORT,
	C_TOKEN_UNSIGNED,
	C_TOKEN_CONTINUE,
	C_TOKEN_FOR,
	C_TOKEN_SIGNED,
	C_TOKEN_VOID,
	C_TOKEN_DEFAULT,
	C_TOKEN_GOTO,
	C_TOKEN_SIZEOF,
	C_TOKEN_VOLATILE,
	C_TOKEN_DO,
	C_TOKEN_IF,
	C_TOKEN_STATIC,
	C_TOKEN_WHILE,
	C_TOKEN_ASM,
	// literales
	C_TOKEN_NUMBER,
	C_TOKEN_DECIMAL,
	C_TOKEN_STRING,
	C_TOKEN_CHARACTER,

	// caso a parte, IDENTIFICADORES
	C_TOKEN_IDENTIFIER,

	// Especiales
	C_TOKEN_NEWLINE,
	C_TOKEN_BACKSLASH,
	C_TOKEN_HORIZONTAL_TAB,
	C_TOKEN_BACKSPACE,
	C_TOKEN_QUESTION_MARK,
	C_TOKEN_SINGLE_QUOTE,
	C_TOKEN_DOUBLE_QUOTE,
	C_TOKEN_CARRIAGE_RETURN,
	C_TOKEN_FORMFEED,
	C_TOKEN_AUDIBLE_ALERT,

	C_TOKEN_WHITE_SPACE, // para cualquier cosa que no queramos

	// carácteres importantes
	C_TOKEN_LEFT_PAREN,
	C_TOKEN_RIGHT_PAREN,
	C_TOKEN_LEFT_BRACKET,
	C_TOKEN_RIGHT_BRACKET,
	C_TOKEN_LEFT_BRACE,
	C_TOKEN_RIGHT_BRACE,
	C_TOKEN_COLON,
	C_TOKEN_SEMICOLON,
	C_TOKEN_COMMA,
	C_TOKEN_DOT,

	// OPERADORES
	C_TOKEN_TERNARY,
	C_TOKEN_ADD,
	C_TOKEN_SUB,
	C_TOKEN_STAR, // *
	C_TOKEN_DIV,
	C_TOKEN_BANG,
	C_TOKEN_AND,
	C_TOKEN_OR,
	C_TOKEN_MOD,
	C_TOKEN_BYTEWISE_AND,
	C_TOKEN_BYTEWISE_OR,
	C_TOKEN_BYTEWISE_NOT,
	C_TOKEN_BYTEWISE_XOR,
	C_TOKEN_LESS,
	C_TOKEN_GREATER,
	C_TOKEN_EQUAL,
	C_TOKEN_ASSIGN,
	C_TOKEN_NOT_EQUAL,
	C_TOKEN_RIGHT_SHIFT,
	C_TOKEN_LEFT_SHIFT,
	C_TOKEN_LESS_EQUAL,
	C_TOKEN_GREATER_EQUAL,
	C_TOKEN_ARROW,
	C_TOKEN_POSTFIX_ADD,
	C_TOKEN_POSTFIX_SUB,
	C_TOKEN_SUB_ASSIGN,
	C_TOKEN_ADD_ASSIGN,
	C_TOKEN_MUL_ASSIGN,
	C_TOKEN_DIV_ASSIGN,
	C_TOKEN_MOD_ASSIGN,
	C_TOKEN_RIGHT_SHIFT_ASSIGN,
	C_TOKEN_LEFT_SHIFT_ASSIGN,
	C_TOKEN_BYTEWISE_OR_ASSIGN,
	C_TOKEN_BYTEWISE_AND_ASSIGN,
	C_TOKEN_BYTEWISE_XOR_ASSIGN,


	// añadidos de MunixCC
	C_TOKEN_ATTRIBUTE,
	C_TOKEN_ASMBLOCK,
	C_TOKEN_SIZE_T,
	C_TOKEN_U32,
	C_TOKEN_I32,
	C_TOKEN_U16,
	C_TOKEN_I16,
	C_TOKEN_U8,
	C_TOKEN_I8,

	C_TOKEN_AS, // para ahorrarme dolores de cabeza cuando haya casts

	// cosas internas
	C_TOKEN_INTERN_NULL, // un error en lexing básicamente

} TokenTypeC;

typedef struct {
	TokenTypeC type; // el tipo de token
	char *start; // inicio de la cadena
	size_t len; // longitud
	int line; // no se si lo usare, pero ahi esta
} TokenC;

#endif
